"use client";

import * as React from "react";
import Image from "next/image";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { DevTag } from "@/components/ui/dev-tag";

// Rotating hero image: an AI-generated on-model shot cross-fades through a set
// of looks. Each is generated by us on a flat #f0f0f0 ground (the same color as
// the hero section), so the figure sits seamlessly with no visible card edge.
const looks = [
  {
    src: "/img/ip/shoot/image_11.png",
    brand: "Marisol",
    prompt: "full-body on-model, tailored suit, soft studio light...",
  },
  {
    src: "/img/ip/shoot/image_04.png",
    brand: "Anna Nova",
    prompt: "on-model evening dress, clean studio, editorial...",
  },
  {
    src: "/img/ip/shoot/image_17.png",
    brand: "Northwind",
    prompt: "full-body tailored pantsuit, neutral ground...",
  },
  {
    src: "/img/ip/shoot/image_24.png",
    brand: "Kestrel",
    prompt: "two-piece set, on-model, soft daylight...",
  },
];

export function HeroRotator() {
  const [i, setI] = React.useState(0);
  const reduce = useReducedMotion();

  React.useEffect(() => {
    if (reduce) return;
    const id = setInterval(() => setI((v) => (v + 1) % looks.length), 8000);
    return () => clearInterval(id);
  }, [reduce]);

  return (
    <div className="relative h-[26rem] w-full overflow-hidden bg-[#F0F0F0] sm:h-[34rem] lg:h-[calc(37rem+10vh)] lg:w-[calc(100%+5rem)]">
      <AnimatePresence initial={false} mode="sync">
        <motion.div
          key={looks[i].src}
          className="absolute inset-0"
          initial={reduce ? false : { opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 1.6, ease: "easeInOut" }}
        >
          <Image
            src={looks[i].src}
            alt={`${looks[i].brand}, AI-generated on-model look`}
            fill
            sizes="(max-width: 1024px) 100vw, 720px"
            className="object-contain object-bottom"
            priority={i === 0}
          />
          {/* Inside the cross-fading layer, so the prompt fades with its image. */}
          <DevTag path="/generate/image/v1" prompt={looks[i].prompt} />
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
