import Image from "next/image";
import { DevTag } from "@/components/ui/dev-tag";

// Auth-screen imagery: one static, AI-generated on-model shot filling the
// full-height left column. The image is generated by us on a flat #f0f0f0 ground
// (same as the panel), so the figure sits cleanly with no hard crop or scrim.
export function AuthHero({
  src = "/img/ip/shoot/image_11.png",
  prompt = "full-body on-model, tailored suit, soft studio light...",
}: {
  src?: string;
  prompt?: string;
}) {
  return (
    <div className="relative hidden h-full overflow-hidden bg-[#f0f0f0] lg:block">
      <Image
        src={src}
        alt="AI-generated on-model look"
        fill
        priority
        sizes="65vw"
        className="object-contain object-bottom"
      />

      <DevTag path="/generate/image/v1" prompt={prompt} corner="br" />

      <h2 className="absolute inset-x-0 bottom-0 max-w-2xl p-12 font-display text-4xl font-medium leading-[1.06] tracking-tight text-fill sm:text-5xl">
        The image AI API for
        <br />
        fashion and ecommerce.
      </h2>
    </div>
  );
}
